### ISSUE TITLE
Old version doesn't work with fabric

### ISSUE THREAD

**Issue by omerien** [Wurst-Imperium/WI-Zoom#27]
I tried install [https://www.curseforge.com/minecraft/mc-mods/wi-zoom/files/3171791](the 1.16) version, but it complains about a 0.12.1 fabric version, which doesn't solve the problem if given.

**Comment by omerien** [comment]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.12.1 or later.
Unmet dependency listing:
	 - Mod 'WI Zoom' (wi_zoom) 1.3-MC1.16.5 requires version 0.12.1 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

**Comment by Alexander01998** [comment]
You are confusing the Fabric API with Fabric Loader. This is an extremely common beginner mistake.
When a Fabric error message says `Install fabric, version X or later.`, it is **always** referring to Fabric API.
You need to install [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api), version 0.12.1 or later (I'd recommend [version 0.29.3](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3159126) in this case), by adding it to your mods folder.

This error message is known to be confusing, but it's not something that I can change. The message is coming from Fabric itself, not from WI Zoom.
